services:
  # app-customer:
  #   build: .
  #   environment:
  #     - PORT=3000
  #     - DB_HOST=localhost
  #     - DB_PORT=5432
  #     - DB_USERNAME=customer_user
  #     - DB_PASSWORD=123456
  #     - DB_NAME=customer_db
  #   ports:
  #     - 3000:3000
  #   links:
  #     - dargaz-market-mysql
  #   depends_on:
  #     - dargaz-market-mysql

  db-postgres:
    image: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db-web-ui:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    links:
      - db-postgres
    depends_on:
      - db-postgres
    environment:
      ADMINER_DEFAULT_SERVER: db-postgres
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db-postgres
      ADMINER_DEFAULT_DB_NAME: customer_db

networks:
  app-network:
    name: app-network
